-- Test-only Prosody config for warden's XMPP connector development (see
-- README's "XMPP" section). Single VirtualHost "localhost", self-signed TLS
-- (auto-generated by the official image on first start), SASL PLAIN enabled
-- via internal_plain storage — deliberately weak/simple since this server is
-- never exposed beyond the compose network and only exists so the connector
-- has something real to talk to. Do not reuse this config for a real
-- federated/public-facing deployment.

admins = { }

modules_enabled = {
    "roster"; "saslauth"; "tls"; "disco";
    "carbons"; "pep"; "private"; "blocklist"; "vcard4"; "vcard_legacy";
    "version"; "uptime"; "time"; "ping";
    "admin_adhoc";
}

allow_registration = false

-- `prosodyctl cert generate` (run once during setup) writes into the data
-- directory, not Prosody's default `<config_dir>/certs` — point the global
-- cert search path there instead of copying files around.
certificates = "/var/lib/prosody"

-- STARTTLS is mandatory — this is exactly the path the connector's Stage 2
-- (STARTTLS upgrade) needs to exercise.
c2s_require_encryption = true
s2s_enabled = false

-- internal_plain stores passwords in a recoverable form (not hashed), which
-- is what lets Prosody offer SASL PLAIN to begin with — some other backends
-- (e.g. internal_hashed/scram) only advertise SCRAM. Test-only tradeoff.
authentication = "internal_plain"

log = {
    info = "*console";
    error = "*console";
}

pidfile = "/var/run/prosody/prosody.pid"

VirtualHost "localhost"

Component "conference.localhost" "muc"
    modules_enabled = { "muc_mam" }
    restrict_room_creation = false
    name = "warden test MUC"
